### ISSUE TITLE
Contao 4.4 display error - EasyThemes Mode: DOM-Inject

### ISSUE THREAD

**Issue by netzarbeiter** [terminal42/contao-easy_themes#29]
![dom-inject-old](https://user-images.githubusercontent.com/1942550/27437050-60b9c9f2-5761-11e7-83d5-a1533865e821.png)

```css
#tl_navigation .easytheme_level_2 {
	padding-left: 40px;
}
.easytheme_level_2_link {
	border-left: none;
}
```
![dom-inject-new](https://user-images.githubusercontent.com/1942550/27437057-66f41192-5761-11e7-9420-db4ff9287587.png)
